ERROR      2024-12-13 14:27:20,817 [main.py:88] データをクリーニング中に何らかのエラーが発生しました
ERROR      2024-12-13 14:30:40,333 [main.py:88] データをクリーニング中に何らかのエラーが発生しました
